name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run build